services:
  lightframe:
    container_name: "lightframe"
    image: lightframe
    ports:
      - '5164:8080'
    environment:
      - ASPNET_SECRETKEYSAUTHENTIC=qweqweqweqweqweqweqweqweqweqweqweqwe
      - ASPNET_ISSUERAUTHENTIC=127.0.0.1
      - ASPNET_AUDIENCEAUTHENTIC=127.0.0.1:5164
      - ASPNETCORE_AAUTHENTIC_DB_SERVER=172.16.0.0
      - ASPNETCORE_AAUTHENTIC_DB_PORT=5432
      - ASPNETCORE_AAUTHENTIC_DB_USER=postgres
      - ASPNETCORE_AAUTHENTIC_DB_PASS=bt7iC4nN07T0f1nDmyp4ss
      - ASPNETCORE_AAUTHENTIC_DB_NAME=lightframe